### ISSUE TITLE
segfaults in Version 4.4.3 / libc-2.13.so

### ISSUE THREAD

**Issue by mkretzer** [haiwen/seafile#1418] opened 2015-10-23 12:09 UTC
Seafile 4.4.3 gets a segfaults in our environment all the time, 4.3.2 on the other hand was absolutely stable (and still works after downgrade).

Here is the syslog:
Oct 23 06:35:01 seafile kernel: [112189.059477] pool[13082]: segfault at 0 ip 00007fe423ef48cf sp 00007fe422e74c58 error 4 in libc-2.13.so[7fe423dda000+181000]

**Comment by freeplant** [comment] 2015-10-23 12:32
This is a known bug caused by syncing of old formatted libraries. It will be fixed in next release in the next week.

**Closed by freeplant** 2015-10-23 12:32 UTC
