### ISSUE TITLE
 [FreeBSD] Seafile utilizes 100% CPU after everything is synced

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile#2036] opened 2018-04-13 18:03 UTC
Hello,

I also mentioned this in the comments of https://github.com/haiwen/seafile-client/issues/604, but this seems to be a much better place.

I've used severl version of Seafile in the last years on several versions of FreeBSD. The issue always happened.

After my libraries are synced, the `seaf-daemon` process occupies 100% CPU time on one core and stays there.

There is nothing unusual in the logs.
It works and sync perfectly fine. Changes are detected on both sides and sync works as it should

I played around with dtrace. While seaf-daemon should be idle and all Libraries are synced, dtrace reports that more than 100K select:entry syscalls are fired within 5 seconds:

```
root@ptrace:~ # dtrace -n 'syscall:freebsd:select:entry /execname == "seaf-daemon"/ { @ = count (); } tick-5s { exit(0); }'
dtrace: description 'syscall:freebsd:select:entry ' matched 2 probes
CPU     ID                    FUNCTION:NAME
  0  81415                         :tick-5s

           100291
```

There is also this comment, where I observed a high amount of context switches: https://github.com/haiwen/seafile-client/issues/604#issuecomment-334960921

Best Regards,
Stefan

**Comment by xkpd3** [comment] 2018-04-15 08:59
Hello,

I'm trying to debug seafile. I've added the `-g` flag to `AM_CFLAGS` in:
- `daemon/Makefile.in`
- `lib/Makefile.in`

I've also added `-g` to `lib/Makefile.in` AM_CPPFLAGS in ccnet client.

However, attaching the debugger to the `seaf-daemon` process shows no debug symbols. Am I doing it wrong? (I have not worked with autotools before)

Best Regards,
Stefan

**Comment by xkpd3** [comment] 2018-04-15 10:41
I rand seafile-daemon for 35 seconds. There was nothing to sync.
I'm not yet sure how to interpret this. But almost the full runtime is consumed by kevent and select is triggered very often (as the dtrace output confirms as well).

```
syscall                     seconds   calls  errors
socketpair              0.000157036       5       0
fdatasync               0.072070752       4       0
geteuid                 0.000032375       1       0
thr_new                 0.000811646      10       0
getuid                  0.000027900       1       0
kqueue                  0.000149541       6       0
getcontext              0.000037057       1       0
getpid                  0.000799339      29       0
__sysctl                0.000566770      15       0
issetugid               0.000481654      10       0
write                   0.005424929      92       0
unlink                  0.000269546       1       0
thr_self                0.000035116       1       0
sysarch                 0.000037548       1       0
socket                  0.000259953       7       0
sigprocmask             0.000584301      19       0
sigaction               0.000071801       2       0
setsockopt              0.000242428      12       0
sendto                  0.000063432       2       0
select                 14.039554004  235459       0
rtprio_thread           0.000035184       1       0
recvfrom                0.000037945       2       0
readlink                0.000055821       1       0
read                    0.691624791     740       3
pread                   0.000043233       1       0
poll                    0.507975552      60       0
pipe2                   0.000507220      16       0
openat                  0.081924590    3727     158
open                    0.001857813      36       1
nanosleep              30.019194342       1       0
munmap                  0.001722277      43       0
mprotect                0.001048355      32       0
mmap                    0.025196487     751       0
lseek                   0.014056646     645       0
kevent                 33.381520229    3620       1
ioctl                   0.000733661      24       2
getsockopt              0.000020666       1       0
getsockname             0.000020493       1       0
getrlimit               0.000080982       2       0
getpeername             0.000022163       1       0
getdirentries           0.012691443     191       0
fstatfs                 0.001210347      34       0
fstatat                 0.446304192   11957    1200
fstat                   0.089469332    4186       0
fcntl                   0.054933827    2438       0
connect                 0.000398837       6       1
close                   0.006350999     134       0
access                  0.009982127     250       0
_umtx_op               20.639620796      48       7
                      ------------- ------- -------
                      100.110317478  264627    1373

time output: 0m34.92s real     0m17.71s user     0m17.47s system
```

**Comment by shoeper** [comment] 2018-04-15 10:46
> I rand seafile-daemon for 35 seconds. There was nothing to sync.

Do I understand it correctly that you've just started it? Every start it first needs to rescan all your stuff because it cannot not what happened in the meantime (It could have been closed for a week, ...)

**Comment by xkpd3** [comment] 2018-04-15 11:29
This is the log that's written when starting seafile (in order, via tail -f): https://gist.github.com/xkpd3/3d9f5f1e9e8d8301f0a048825fd1adf8

**Comment by xkpd3** [comment] 2018-04-15 11:35
After playing around, I figured out that the CPU utilization goes back to normal when I "unsync" my  "DeviceSync-iPhone8" library.

So the devil's in there. That would explain the high number of errornous `fstatat` calls.

Is there a way to figure out which files are causing the problem?

**Comment by xkpd3** [comment] 2018-04-15 12:05
This library has only two folders. I have delete all files *in* these folders locally. My assumption was, that if seafile deletes all files on the server, only the ones that were not synced remain on the server.

Unfortunately all files got deleted from the server. So all files were correctly synced.

By playing around further I noticed that the CPU utilization is below 20% while syncing. Once everything is synced, the CPU goes up to 100%.

I'm not gradually syncing the files back to try to find out which batch of files creates the issue. I first thought about a strange file name, but all files are named after a similiar pattern without any unusual characters.

**Comment by xkpd3** [comment] 2018-04-25 19:08
Hello,

In this file, I recorded the output of the first 10 seconds after `seaf-cli start`.
https://shell.srv.hagen.coffee/~sdk/seafile_truss.tgz2

You can see that the libraries are getting synced and then a loop is happening.

This line repeats over and over and over again. I first recorded 10 minutes, but it ended up to be a 1.5gb file with nothing than this loop.

```
select(3542,{ 18 25 29 1034 1035 1039 1042 1043 1045 1046 1059 1100 1103 1106 1107 1109 1110 1123 1160 1162 1164 1165 1166 1167 1170 1171 1172 1173 1174 1175 1176 1177 1187 1219 1220 1223 1224 1229 1230 1231 1233 1234 1235 1236 1237 1238 1239 1240 1241 1251 1288 1290 1292 1293 1294 1295 1298 1299 1300 1301 1302 1303
1304 1305 1315 1351 1352 1356 1361 1362 1366 1370 1379 1415 1416 1421 1422 1423 1425 1426 1427 1428 1429 1430 1431 1432 1433 1443 1474 1475 1477 1478 1479 1480 1481 1482 1483 1487 1488 1489 1490 1492 1493 1494 1497 1507 1539 1540 1546 1547 1551 1552 1664 1666 1668 1670 1671 1672 1674 1675 1729 1730 1731 1732 1733 1734 1735 1736 1738 1742 1743 1744 1745 1746 1748 1749 1750 1753 1763 1800 1801 1802 1803 1806 1807 1808 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1822 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836 1837 1838 1858 1860 1862 1864 1868 1869 1871 1872 1873 1874 1876 1877 1878 1881 1891 1924 1925 1926 1927 1928 1930 1931 1934 1935 1937 1938 1939 1940 1941 1942 1943 1944 1945 1955 2048 2050 2052 2054 2055 2056 2058 2059 2118 2123 2124 2125
2127 2128 2129 2134 2138 2147 2209 2210 2212 2213 2218 2221 2222 2225 2229 2230 2232 2234 2236 2237 2240 2241 2242 2244 2245 2249 2250 2252 2253 2256 2258 2260 2261 2267 2268 2269 2272 2274 2275 2277 2280 2285 2286 2289 2290 2292 2293 2297 2300 2301 2304 2309 2310 2312 2314 2315 2317 2322 2324 2325 2328 2329 2332 2333 2340 2341 2346 2349 2350 2352 2354 2355 2357 2363 2364 2365 2370 2373 2374 2377 2380 2381 2385 2386 2389 2390 2392 2394 2395 2397 2400 2401 2404 2405 2409 2413 2414 2418 2421 2422 2424 2429 2430 2432 2437 2438 2440 2441 2444 2445 2450 2453 2454 2458 2460 2461 2464 2468 2469 2476 2477 2482 2484 2485 2491 2492 2493 2504 2505 2506 2507 2509 2515 2517 2518 2520 2521 2522 2523 2525 2526 2528 2530 2531 2533 2534 2536 2538 2541 2542 2544 2545 2546 2547 2549 2552 2553 2556 2557
2558 2562 2565 2566 2568 2569 2571 2573 2574 2576 2577 2578 2579 2581 2584 2585 2588 2590 2592 2594 2597 2598 2600 2605 2606 2609 2610 2613 2614 2616 2619 2621 2622 2626 2627 2629 2630 2632 2634 2637 2638 2640 2641 2642 2643 2645 2649 2650 2651 2654 2656 2657 2658 2659 2661 2662 2666 2668 2669 2670 2672 2674 2677 2678 2680 2681 2684 2685 2686 2688 2689 2692 2694 2696 2699 2700 2701 2702 2705 2706 2707 2709 2710 2712 2713 2717 2718 },0x0,0x0,0x0) = 464 (0x1d0)
```

I tried to debug with gdb, but I'm getting lost in all those threads. Do you have a suggestions where to place a breakpoint for a start?

**Comment by freeplant** [comment] 2018-10-30 06:42
I'm sorry this is beyond our support range. As the issue is old, I will close it.

**Closed by freeplant** 2018-10-30 06:42 UTC

**Comment by mmance** [comment] 2022-04-30 15:35
The issue may be old, but its 2022 and I get the exact same issue on my freeBSD 13.  Must be file specific, cause I unsync my photos library and the issue goes away.  Would be nice to know whats going on here.
