### ISSUE TITLE
Library rename is reverted after sync

### ISSUE THREAD

**Issue by guido-osict** [haiwen/seafile#1714] opened 2016-07-08 13:29 UTC
Hi,
- I rename a synced Library with the API (https://myserver/api2/repos/...repo_id.../?op=rename)
- The (Windows or OSX) client will show the new Library name after some seconds
- The local foldername (Windows or OSX) is not changed
- If I add a new file in the synced folder, the name of the library in seafile is changed back to the original library name.

Server Version: 5.1.3 
Server Version: Apache/2.4.6 (CentOS)
Seafile Client (osx) 5.1.1 

![screen shot 2016-07-08 at 15 24 49](https://cloud.githubusercontent.com/assets/20356116/16688843/535097a4-4520-11e6-893f-c1906d728b7d.png)

**Comment by guido-osict** [comment] 2016-08-31 13:14
anybody?

**Comment by killing** [comment] 2016-09-06 10:39
This is a known issue. That's because Seafile stores library name inside the change history. So there is a chance that, when you change the library name and some files at close time (within 30 seconds), the name would be reverted. We're still looking solution to this issue. But it's not high priority in our schedule.

**Comment by freeplant** [comment] 2018-10-30 07:47
The problem is already fixed in our latest version.

**Closed by freeplant** 2018-10-30 07:47 UTC
