### ISSUE TITLE
Seafile overwrites new file with an old one when permissions are wrong on a different PC

### ISSUE THREAD

**Issue by rominf** [haiwen/seafile#819] opened 2014-08-26 13:51 UTC
I have an file F on 2 computers A and B.
I edited file F on a computer A, saved it, seaflie-applet synced it with server (I've checked that via web-interface). I've checked this file on a computer B, but it was an old version of file. Just after viewing file, seaf-cli changed it's status to commiting and uploaded an old version of file to the server. After that seafile-applet (on A) overwrote a file with an old version. This also happens even without viewing F on B. I've got F overwrited by seafile-applet every 2-10 minutes while editing it in vim.

I've found that the problem was wrong permissions of file F on B. But all I found in logs was:
```
Failed to checkout file F.
```
I think it's not enough.

Things to be done:
1. Check the reason of checkout failure (permissions) and print it to the logs.
2. Write about permission problems on the PC_NAME with file F in the web interface, GUI and CLI.
3. Stop syncing this file as it produces bad results.

**Comment by freeplant** [comment] 2015-10-12 04:21
We can't reproduce the problem. So I will close the issue.

**Closed by freeplant** 2015-10-12 04:21 UTC
Labels: accept
