### ISSUE TITLE
Firefox 34: Missing Share Button On Libraries

### ISSUE THREAD

**Issue by papst01** [haiwen/seafile#1001] opened 2014-12-31 12:27 UTC
Server: 4.0.3 32bit on a Debian
Client: Windows 7 with Firefox 34

There is no button to share libraries, even the standard library couldn't be shared, only the delete button is available. Chrome resp. Iron shows both button. See attached screenshot.

![seafilebug](https://cloud.githubusercontent.com/assets/6513409/5587633/af5e7fec-90f0-11e4-940c-ded732f5a30c.PNG)

**Comment by iBigQ** [comment] 2015-01-06 16:55
same for me
Server 4.0.3 and Linux Firefox 34

**Comment by shoeper** [comment] 2015-01-07 14:07
On one of my devices it is missing in Chrome, too.

**Comment by tfohlmeister** [comment] 2015-01-09 14:56
I had the same problem with Chromium (=OpenSource Chrome) on Linux. Turned out a Privacy plugin blogged the actual share image. I guess this happend based on the file name, which in this case is `share_20.png`.
You can inspect such errors by opening up the devloper console (press `F12` in Chrome/Chromium and Firefox/Iceweasel) and switch to the `Console` tab. You should find errors there if the icon isn't shown. In my case it was an `ERR_BLOCKED_BY_CLIENT` which clearly indicated that one of my plugins denied access to this very file.

**Comment by lins05** [comment] 2015-01-09 15:09
Interesting. Why doesn't the plugin like the the share button image?

**Comment by tfohlmeister** [comment] 2015-01-09 15:12
I have no idea, probably simply because of that file name. I am using uBlock (https://github.com/gorhill/uBlock).

**Comment by lins05** [comment] 2015-01-09 15:21
So we can close this issue now, since it's not a problem of seafile itself?

**Comment by papst01** [comment] 2015-01-09 15:33
I think we could close it.
The error wasn't shown in my developers console but the hint with the plugin hit! For me and my Firefox it was the add block plus plugin!
-> Plugin disabled, site reloaded -> button was visible
-> Plugin enabled again, site reloaded -> button was gone

**Comment by shoeper** [comment] 2015-01-09 22:46
Can confirm it's no seafile problem.
It's caused by using this adblock blocklist: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt

**Closed** 2015-01-10 02:49 UTC
