### ISSUE TITLE
Activated user creation

### ISSUE THREAD

**Issue by 23degrees** [haiwen/seafile#2008] opened 2018-01-22 04:50 UTC
I can create a working and active account via web browser by accessing one URL. Can I report this here or by email is better?

**Comment by freeplant** [comment] 2018-01-22 08:31
It is better to report the issue to info@seafile.com

**Comment by 23degrees** [comment] 2018-01-22 08:56
I'll send it there.

**Comment by freeplant** [comment] 2018-01-24 02:27
The problem is fixed in version CE 6.2.5 and PRO 6.2.7

**Comment by freeplant** [comment] 2018-01-24 02:27
Thank you very much.

**Closed by freeplant** 2018-01-24 02:27 UTC
