### ISSUE TITLE
Huge seafile.log file after running for a few hours.

### ISSUE THREAD

**Issue by wolfcry0** [haiwen/seafile#1683] opened 2016-06-08 22:24 UTC
I've been having a problem with the seafile client filling up my SSD in the span of a few hours because the seafile.log file grows rapidly with this entry:

`[06/08/16 15:52:10] read pipe error`
`[06/08/16 15:52:10] read pipe error`
`[06/08/16 15:52:10] read pipe error`
`[06/08/16 15:52:10] read pipe error`

According to the windows resource monitor seafile is writing to seafile.log at roughly 2.5MB/s which is a huge amount of data for a log file.

I did a fresh install of version 5.1.2 (removed seafile, removed ccnet folder), but the problem is still there.

This is on a windows 10 x64 system, client version 5.1.2, no AV installed other than windows defender, windows firewall is disabled, MS EMET installed.

Server is centos with version 5.0.7

Last few lines from ccnet.log:

`[06/08/16 12:27:57] ../common/peer.c(943): Local peer down`
`[06/08/16 12:27:57] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)`
`[06/08/16 12:27:57] ../common/peer.c(943): Local peer down`
`[06/08/16 12:27:57] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)`
`[06/08/16 12:27:57] ../common/peer.c(943): Local peer down`
`[06/08/16 13:47:57] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)`
`[06/08/16 13:47:57] ../common/peer.c(943): Local peer down`
`[06/08/16 15:52:10] ../common/peer.c(943): Local peer down`
`[06/08/16 15:52:10] ../common/peer.c(941): libevent got an error! what=33, errno=0 (No error)`
`[06/08/16 15:52:10] ../common/peer.c(943): Local peer down`

**Comment by shoeper** [comment] 2016-06-09 06:49
Duplicate of https://github.com/haiwen/seafile-client/issues/800

You can post your content as comment ;)

**Closed by shoeper** 2016-06-09 06:49 UTC
