### ISSUE TITLE
[Feature Request] Dialog/message while waiting for download

### ISSUE THREAD

**Issue by kulverstukas1** [haiwen/seafile#1253] opened 2015-05-30 19:01 UTC
This would be very useful to regular users - I run seafile on raspberry and downloading a whole directory with big files takes some time to zip it up, while the rpi is zipping it up, no dialog is being shown, and to regular users that is confusing, because nothing appears for some time, so they click again and again. The way I see it, Seafile should show some kind of a message or a dialog while the user is waiting for that download link to appear (while Seafile is zipping up a file), even better would be a progress bar :)

**Comment by iBigQ** [comment] 2015-06-11 07:15
Related to https://github.com/haiwen/seahub/issues/267

**Comment by shoeper** [comment] 2016-02-09 23:33
duplicate of https://github.com/haiwen/seahub/issues/267

**Closed by shoeper** 2016-02-09 23:33 UTC
