### ISSUE TITLE
cosmetic issue with library sharing in v6.1.0

### ISSUE THREAD

**Issue by shpokas** [haiwen/seafile#1904] opened 2017-05-26 06:06 UTC
Issue:
When user tries to share a link to himself, error message appears in Web UI:
"Internal Server Error"

Steps to reproduce:
select a file, try to share to the same user.
1) open a library
2) click on "Share"
3) click on "Share to User"
4) select same user who "owns" the file in drop down box
5) click on "Submit"

Observed result:
Error message appears
"Internal Server Error"

Expected result:
Anything else explaining wrong action.

Note that in seahub.log correct error message is written:
2017-05-26 09:00:12,980 [ERROR] seahub.api2.endpoints.dir_shared_items:337 put Can not share repo to myself

It is just Web UI that is not handling this action.
<img width="743" alt="screen shot 2017-05-26 at 11 29 13" src="https://cloud.githubusercontent.com/assets/1006081/26482893/866a7936-4207-11e7-980e-8daee26d30c0.png">

**Comment by freeplant** [comment] 2018-10-30 09:44
The issue is fixed in the latest version.

**Closed by freeplant** 2018-10-30 09:44 UTC
