### ISSUE TITLE
Make the setup procedure automation friendly.

### ISSUE THREAD

**Issue by bartmeuris** [haiwen/seafile#930] opened 2014-11-17 09:23 UTC
Right now it's a nightmare to automate an install. The setup:
- assumes too much and tries to create directories where it does not necessarily has permission
- is interactive, without any means of providing the required settings on the command line
- If you create empty directories to counter the above problem (the ccnet for example), the setup fails because it thinks the config already exists.
- when setting up with mysql it wants to connect to the database, even if I told it that they already exist. In my case they will exist in production, that will be handled by something else, but now during automation I have to install some temporary database server or patch the installer -> a major pain in the ass.
- when starting the hub the first time, the startup procedure asks for an admin email and password, which makes this very painful in a headless environment.

I finally succeeded, but I had to reverse-engineer the setup script and write a python script to create a default admin account. The problem is that if some aspect of the installation procedure is updated in the future, my installation procedure will break.

A much cleaner and more practical way would be:
- Let the installer accept command-line parameters for everything.
- Do not ask for admin user/password during startup, move this to the installation procedure.
- Centralize configuration. Right now it's spread over multiple files and directories.
- provide a way not to let the servers start as daemon, but stay in foreground. The startup scritps simply do too much. I tried looking into them, but gave up.

**Comment by makkus** [comment] 2015-02-09 03:55
Any news on this? As far as I can see the answer-file solution wasn't merged yet. At least that would be a start. Being able to do an automated setup is really getting more and more important nowadays, esp. considering technologies like linux containers and such.

I appreciate how relatively easy seafile is to setup for a new user in a non-professional/home environment, but that actually seems to make seafile indefinitely harder to setup in more involved environments (automated VM and Linux container setups, for example). 
The lack of proper packaging, the non-standard organisation of config and init files and not being able to automate an install is, for me at least, the biggest flaw (along with some security related concerns I have) of this otherwise very nice piece of software.

So, given @lins05 's response and the fact that the answer-file solution wasn't merged even though the pull request is a few month old, I guess there are no plans to do any substantial work in that area and make seafile a bit more 'enterprise-friendly', is that correct?

**Comment by freeplant** [comment] 2015-02-09 14:19
The best way to solve the problem is not using the seafile.sh and seahub.sh. But writing some new scripts to set up the required environment, to run ccnet-server, seaf-server and seahub. The seafile-controller is not needed at all. Just as we do in developing environment.

**Comment by itsafire** [comment] 2015-03-08 18:43
I tried to re-use seafile-admin. have a look at seafile-ni-setup (non-interactive).

{% gist ff2ea47cd6e7c7c697d7 %}

'''
usage: seafile-ni-setup [-h] [--seafile_port SEAFILE_PORT]
                        [--seafile_fileserver_port SEAFILE_FILESERVER_PORT]
                        [--ccnet_port CCNET_PORT]
                        servername ipdomain seafile_base_path
seafile-ni-setup: error: too few arguments
'''

**Closed** 2020-09-16 09:16 UTC
