### ISSUE TITLE
libcurl, Couldn't resolve host name, ipv6

### ISSUE THREAD

**Issue by dbruenig** [haiwen/seafile#1268] opened 2015-06-03 22:10 UTC
Symptom: "When downloading a library, the client hangs at "connecting server""

windows client, version 4.2.2
from the seafile.log:
http-tx-mgr.c(639): libcurl failed to GET https:// ... :  Couldn't resolve host name.

I suspect it is related to me using ipv6 now (curl tried to get AAAA records) since it worked with A record fetching before and I just switched over to ipv6 networking.

Sorry, I didnt investigate further except that using a more recent libcurl version from here, for example, 
http://www.paehl.com/open_source/?CURL_7.42.1
did solve the problem in my case.

**Comment by Chilledheart** [comment] 2015-06-04 04:12
Hi @dbruenig ,
It is interesting. In fact, I made a test package for ipv6 support issue. The package is based on 4.2.3 release and contains a upgraded curl. Could you test it for verifying if the issue is solved so that we can add this fix for the next release?

download: https://seacloud.cc/f/6561e54e84/
9d6666e4ea53ee6f64f27872dab792d26b490a26b0aacd8d1353cb36ffea5fdc  seafile-4.2.3-en-ipv6.msi

**Comment by dbruenig** [comment] 2015-06-04 11:17
Hi @Chilledheart 
I downloaded your installer (seafile-4.2.3-en-ipv6.msi), removed the old installed files, then installed the msi and finally I restored my config files. 

It seems resolving aaaa records still causes this error in the log file:

[06/04/15 13:12:29] http-tx-mgr.c(639): libcurl failed to GET https://example.com/seafhttp/protocol-version: Couldn't resolve host name.

**Comment by dbruenig** [comment] 2015-06-04 12:35
I built the dll with Visual Studio 2012, the following options were set by default (just by running 
**nmake /f Makefile.vc mode=dll**
 in winbuild directory):

Using SSL:
Using c-ares:
Using SSH2:
Using ZLIB:
Using IDN: true
Using IPv6: true
Using SSPI: true
Using WinSSL: true
CFLAGS: /I. /I ../lib /I../include /nologo /W3 /EHsc /DWIN32 /FD /c /DBUILDING_LIBCURL /I../../deps/include /DUSE_WIN32_IDN /DWANT_IDN_PROTOTYPES /DUSE_IPV6 /DUSE_WINDOWS_SSPI /DUSE_SCHANNEL
LFLAGS: /nologo /machine:x86 /LIBPATH:../../deps/lib
GenPDB:
Debug:
Machine: x86

**Comment by Chilledheart** [comment] 2015-06-04 20:40
Thank you, @dbruenig.
I updated `seafile-4.2.3-en-ipv6.msi` and could you try this new package? I can confirm option IPV6 was not turned on for some reason in the first test package, but I think it should work now.

download: https://seacloud.cc/f/6561e54e84/
sha256sum: ae7da6c25e9c176a8eb0e9e3ce60a94c565e1f8d50b80c13ceb4fca2bd77905a

**Comment by dbruenig** [comment] 2015-06-04 21:59
Yes, now it works.

**Comment by Chilledheart** [comment] 2015-06-05 01:54
@dbruenig Thanks for confirming it!

**Comment by Chilledheart** [comment] 2015-06-05 01:57
This bug is marked as fixed

**Closed by Chilledheart** 2015-06-05 01:57 UTC
