### ISSUE TITLE
feature request: option to ignore git/svn... repositories

### ISSUE THREAD

**Issue by Alcatr4zz** [haiwen/seafile#1037] opened 2015-01-20 23:16 UTC
Having repositories like git, svn, bzr, hg... within a Seafile library can sometimes be quite a pain, especially when you're working a lot with branches. Every time a branch is switched, Seafile resyncs the whole folder, which can be quite confusing when the library is synced to multiple computers.

Of course, a solution could be to include every single repository within seafile-ignore.txt, but that can be quite exhausting.

A good start would be to add an option to ignore folders containing .git, .svn ... subfolders.
A lot more complex (and thus not part of this feature request) would be the detection whether the repository is a remote repository or just a local one (e.g. in the case of git). For the latter the desired behavior may be that Seafile still syncs the folder.

**Comment by rockfreak** [comment] 2015-02-02 12:12
I would also appreciate being able to globally ignore the .git folder

**Comment by shoeper** [comment] 2015-02-02 17:23
I think a good start would be adding an option to configure an ignore list for the whole device. Even better would be to sync selected entries with all devices being logged in with the same account. Or maybe also something on library level.

**Comment by priyadarshan** [comment] 2015-02-16 10:18
It seems technically it is possible to ignore directories, but there may be a bug: https://groups.google.com/forum/#!topic/seafile/EKB3fZmz49k

**Comment by CharlesNepote** [comment] 2015-02-20 12:44
I have the same problem.
I created a seafile-ignore.txt file and try many options:
.git
.git*
.git/
.git/*
.git/*.*

But .git/ and subdirectories of .git/objects/ are still synced.

**Comment by shoeper** [comment] 2015-02-20 13:05
Please try also with a leading `/`

**Comment by CharlesNepote** [comment] 2015-02-20 17:36
Doesn't change anything with a leading /

My test:
$ rm -fr ./.git/
$ git init        # sync ./.git/ in Seafile repo (but only ./.git/ not its subdirectories)
$ git add *    # sync ./.git/objects/ and its subdirs in Seafile repo (but no files, only directories)

My seafile-ignore.txt
.git
.git*
.git/
.git/*
.git/*.*
/.git
/.git*
/.git/
/.git/*
/.git/*.*

**Comment by shoeper** [comment] 2015-02-20 18:29
for me `*.git/*` works well (Just tested).
Ignores all repositories in the whole library.

**Comment by Alcatr4zz** [comment] 2015-02-20 19:17
Don't get me wrong here. This feature request was not meant for just ignoring the .git folder (which works great for me for a long time with rules you already mentioned (`*.git/`)).
Instead, also the folders *containing* the .git folder shall be ignored.

**Comment by shoeper** [comment] 2015-02-20 19:33
That's something else and the thing this repo was initially for.
But CharlesNepote said ignoring .git folders isn't possible so far/does not work - but it does.

**Comment by rmmonster** [comment] 2015-03-16 16:37
@shoeper I have the same issue as @CharlesNepote and started a [new issue](https://github.com/haiwen/seafile/issues/1137) for this problem

**Comment by shoeper** [comment] 2015-03-16 18:03
This feature (the one requested by Alcatr4zz) could be implemented by checking if `git` (or the other commands) are available via command line. If so Seafile could run git status for each folder and when it says `On branch.*` it's a repo otherwise it isn't. Easiest way would be adding path to seafile-ignore.txt automatically on finding some new folder (and improving seafile-ignore.txt's behaviour).

**Comment by sjentzsch** [comment] 2015-05-12 12:38
I have the same issues as @CharlesNepote and @rmmonster: 

My seafile-ignore.txt looks like:

```
*.git
*.git/
.git*
.git/
*.git/*
bbu/
bbu/.git/*
bbu/.git/objects/pack/
```

... and still, every time I create the bbu/ git repository, the folder and the subfolder .git/ are synced, without any other content. And YES the seafile-ignore.txt is in the root directory and works.

I consider this as a bug.

**Comment by zeze0556** [comment] 2015-07-03 02:39
same issues.
.git only ignore root directory
*/.git  not ignore directory in the subdirectory

**Comment by hville** [comment] 2015-07-13 01:05
The problem is the first dot in an expression. The following works for me:
either 
1. use "?git/" and "*/.git/" to cover the root and subfolders. Both are needed. 
Possible false positives like /Agit/
or
2. use "*git/". 
Shorter but possible false positive like "/i.AmNot.git/"

**Comment by hville** [comment] 2015-07-13 01:24
Actually. I found that just `*.git/` is simple compromise. It is unlikely that I use a `/sub/le.git/` folder unless looking for trouble

**Comment by killing** [comment] 2016-02-15 08:08
Fixed in latest version.

**Closed** 2016-02-15 08:08 UTC
