### ISSUE TITLE
Encryption password entry: Enter key opens file browser

### ISSUE THREAD

**Issue by nyanpasu64** [haiwen/seafile#1375] opened 2015-09-11 07:37 UTC
When entering a password when syncing a library, pressing Enter opens the file browser window instead of submitting the dialog.

Seafile 4.3.3 on Windows 7 x64.

**Comment by lins05** [comment] 2015-09-11 10:11
Thanks for reporting. We'll recheck and fix it.

**Comment by w0xz** [comment] 2015-10-29 11:33
I can confirm this bug also existing in 4.4.2 on Windows 8

**Comment by shoeper** [comment] 2016-02-09 23:39
Has it been fixed in v 4.4?

**Comment by shoeper** [comment] 2016-03-31 13:14
On Fedora the select folder dialog is being opened, so it looks like this small usability issue is still there.

**Closed** 2020-09-16 09:20 UTC
Labels: priority-low, type-bug
