### ISSUE TITLE
WebDAV upload error

### ISSUE THREAD

**Issue by martimarkov** [haiwen/seafile#1196] opened 2015-04-23 12:29 UTC
Hi, I'm using Seafile with nginx. When I upload a file through the web interface everything is fine but when I try to upload through the WebDAV interface it gives me this error:

```
[2015-04-17 03:36:52,777]:  PUT: byte copy failed
Traceback (most recent call last):
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/wsgidav/request_server.py", line 720, in doPUT
    readbuffer = environ["wsgi.input"].read(n)
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/flup-1.0-py2.6.egg/flup/server/fcgi_base.py", line 161, in read
    self._waitForData()
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/flup-1.0-py2.6.egg/flup/server/fcgi_base.py", line 147, in _waitForData
    self._conn.process_input()
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/flup-1.0-py2.6.egg/flup/server/fcgi_base.py", line 673, in process_input
    rec.read(self._sock)
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/flup-1.0-py2.6.egg/flup/server/fcgi_base.py", line 492, in read
    raise EOFError
EOFError
[2015-04-17 03:36:52,860]:  Traceback (most recent call last):
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/wsgidav/error_printer.py", line 43, in __call__
    for v in app_iter:
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/wsgidav/request_resolver.py", line 201, in __call__
    for v in app_iter:
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/wsgidav/request_server.py", line 113, in __call__
    app_iter = method(environ, start_response)
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/wsgidav/request_server.py", line 738, in doPUT
    self._fail(e)
  File "/xxx/seafile-server-4.1.2/seahub/thirdpart/wsgidav/request_server.py", line 128, in _fail
    raise e
DAVError: DAVError(500 Internal Server Error: An internal server error occurred
    Source exception: '')

[2015-04-17 03:36:52,861]:  e.srcexception:

[2015-04-17 03:36:53,468]:  Input stream not completely consumed: closing connection
[2015-04-17 03:36:53,469]:  Adding 'Connection: close' header
```

Any ideas?

**Comment by lins05** [comment] 2015-04-24 02:10
Can you show your `seafdav.conf` and nginx config for seafile webdav server?

**Comment by martimarkov** [comment] 2015-04-24 02:16
/xxx/conf/seafdav.conf:

```
[WEBDAV]
enabled = true
port = 8080
fastcgi = true
share_name = /seafdav
```

**Comment by martimarkov** [comment] 2015-04-24 02:20
nginx:

```
        fastcgi_pass    127.0.0.1:8080;
        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO           $fastcgi_script_name;

        fastcgi_param   SERVER_PROTOCOL     $server_protocol;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param   SERVER_ADDR         $server_addr;
        fastcgi_param   SERVER_PORT         $server_port;
        fastcgi_param   SERVER_NAME         $server_name;
        fastcgi_param   REMOTE_ADDR         $remote_addr;
		
        client_max_body_size 0;
		proxy_ignore_client_abort on;
        proxy_buffering off;
		proxy_connect_timeout  36000s;
		proxy_read_timeout  36000s;

        access_log      /var/log/nginx/seafdav.access.log;
        error_log       /var/log/nginx/seafdav.error.log;
```


I have tested uploading a small file (jpeg) and it gets uploaded without a problem but if I try to upload a 2GB mp4 file it always gives me an error.

**Comment by martimarkov** [comment] 2015-04-24 02:21
I have added:

```
        client_max_body_size 0;
        proxy_ignore_client_abort on;
        proxy_buffering off;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
```

one by one in order to test if that will make a difference and it doesn't...

**Comment by shoeper** [comment] 2015-04-24 13:02
These
```
        proxy_ignore_client_abort on;
        proxy_buffering off;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
```
don't have any effect for fastcgi. They are only required for http/s client sync, but that has nothing to do with WebDAV.

**Comment by martimarkov** [comment] 2015-04-24 13:05
Well I tried without them before that and I only added them as a method of last resort. I don't know where the problem is coming from. They shouldn't even affect the WebDAV.

**Comment by martimarkov** [comment] 2015-04-24 13:05
Also /var/log/nginx/seafdav.error.log; is empty.

**Comment by shoeper** [comment] 2015-04-24 13:06
ok, can you have a look at your nginx log (access log)?

**Comment by martimarkov** [comment] 2015-04-24 13:16
For that error this should be the access log:

```
152.78.**.** - - [17/Apr/2015:03:10:00 +0200] "OPTIONS /seafdav/ HTTP/1.1" 401 142 "-" "Transmit/4.4.5 neon/0.29.3"
152.78.**.** - xxx@icloud.com [17/Apr/2015:03:10:01 +0200] "OPTIONS /seafdav/ HTTP/1.1" 200 0 "-" "Transmit/4.4.5 neon/0.29.3"
152.78.**.** - xxx@icloud.com [17/Apr/2015:03:10:01 +0200] "PROPFIND /seafdav/ HTTP/1.1" 207 262 "-" "Transmit/4.4.5 neon/0.29.3"
152.78.**.** - xxx@icloud.com [17/Apr/2015:03:10:01 +0200] "PROPFIND /seafdav/Movies/ HTTP/1.1" 207 269 "-" "Transmit/4.4.5 neon/0.29.3"
152.78.**.** - xxx@icloud.com [17/Apr/2015:03:10:02 +0200] "MKCOL /seafdav/Movies/The%20Lives%20Of%20Others%20%5BDas%20Leben%20Der%20Anderen%5D.2006.BRRip.XviD-VLiS/ HTTP/1.1" 201 376 "-" "Transmit/4.4.5 neon/0.29.3"
152.78.**.** - xxx@icloud.com [17/Apr/2015:03:10:03 +0200] "PROPFIND /seafdav/Movies/The%20Lives%20Of%20Others%20%5BDas%20Leben%20Der%20Anderen%5D.2006.BRRip.XviD-VLiS/ HTTP/1.1" 207 352 "-" "Transmit/4.4.5 neon/0.29.3"
152.78.**.** - xxx@icloud.com [17/Apr/2015:03:36:52 +0200] "PUT /seafdav/Movies/The%20Lives%20Of%20Others%20%5BDas%20Leben%20Der%20Anderen%5D.2006.BRRip.XviD-VLiS/The%20Lives%20Of%20Others%20%5BDas%20Leben%20Der%20Anderen%5D.2006.BRRip.XviD-VLiS.avi HTTP/1.1" 499 0 "-" "Transmit/4.4.5 neon/0.29.3"
93.152..**.** - xxx@icloud.com [17/Apr/2015:03:37:07 +0200] "PUT /seafdav/Movies/Hot%20Fuzz%20(2007)%20%5B1080p%5D/Hot.Fuzz.2007.1080p.BRrip.x264.GAZ.YIFY.mp4 HTTP/1.1" 400 0 "-" "Transmit/4.4.5 neon/0.29.3"
```

**Comment by shoeper** [comment] 2015-04-24 14:01
HTTP code 400 is bad request.
> HTTP 499 in Nginx means that the client closed the connection before the server answered the request. In my experience is usually caused by client side timeout. As I know it's an Nginx specific error code. - http://stackoverflow.com/a/18410932

**Comment by martimarkov** [comment] 2015-04-24 14:03
Yeah, I looked at that error message. But I tried many WebDAV programs and I don't know if there is a setting on the clients side I should modify that would fix the issue. I was wondering if there is way to stop that from the server side?

**Comment by shoeper** [comment] 2015-04-24 14:05
If it's a client timeout then you cannot do anything on the server side.

Which client are you using?

**Comment by martimarkov** [comment] 2015-04-24 14:06
Transmit & Cyberduck.

**Comment by shoeper** [comment] 2015-04-24 14:11
Seems like that's a bug in Transmit and there is a chance you can set the timeout up in Cyberduck, have a look at the settings (if cannot find something for WebDAV, try increasing for ftp - maybe it's used for both).

**Comment by martimarkov** [comment] 2015-04-24 15:27
I tried https://nolobe.com/interarchy/ as well and still the same error. I can't find any settings for timeout. And also timeout doesn't really make sense. I mean as long as there is data transmitted there shouldn't be a timeout from the client's side.

**Comment by shoeper** [comment] 2015-04-24 15:40
Afaik WebDAV in Seafile uses one connection per file and clients have no oppertunity to continue uploads. It could be that your client limits time per connection. You could e.g. upload /dev/null on Linux accidentially and the upload would never finish. So there could be some good reason for such a timeout.

**Comment by martimarkov** [comment] 2015-04-24 15:44
I read that when upload a file using the browser it calculates the blocks on the server. So I was thinking maybe when the upload finishes, it starts to calculate the blocks and the client has no more data to send so it closes the connection but webdav does not reply until the calculations of blocks. This is why it gives the error and stops the calculations of blocks because there was an error and it propagates? 

Idk it's just an idea. Any opinion?

**Comment by martimarkov** [comment] 2015-04-24 15:45
Also it's a bit strange that all the clients do this. I'm uploading a 4 GB file in less than 10 minutes. I can't belie I'm the only person who uploads something using WebDAV and I'm pretty sure other people will have tried uploading for more than 10 minutes.

**Comment by martimarkov** [comment] 2015-05-06 03:43
@shoeper can you please verify if you can upload files above 4GB using webdav?

**Comment by martimarkov** [comment] 2015-05-06 09:49
I tried without nginx to upload a file by having 
fastcgi = false
and I still get the same error. This means the problem lies with seafdav and not the configuration.

**Comment by shoeper** [comment] 2015-05-06 10:11
@martimarkov I cannot test it because I've set the upload limit to 2GiB (I don't use the mobile client or webinterface for big uploads - I mainly use the Desktop Client).

Uploads beyond 4GiB can be tricky - no matter if you use Seafile or some other software.
E.g. nginx first caches the whole post request and passes it after the upload has been finished to fcgi (maybe this has been fixed in the latest version but I wou
er if you use Seafile or some other software.
Nginx first caches the whole post request and passes it after the upload has been finished to fcgi (maybe this has been fixed in the latest version but I wouldn't count on that). Furthermore keep in mind that the Server has to calculate blocks and that needs some time (the more the bigger the file is). Furthermore uploading big files is not supported by all systems and need a 64-bit system.

```
I read that when upload a file using the browser it calculates the blocks on the server. So I was thinking maybe when the upload finishes, it starts to calculate the blocks and the client has no more data to send so it closes the connection but webdav does not reply until the calculations of blocks. This is why it gives the error and stops the calculations of blocks because there was an error and it propagates?
```
This idea isn't bad but I can not tell you how it works in detail. Maybe @freeplant can tell us if this could be an issue.

**Comment by martimarkov** [comment] 2015-05-12 04:58
I'm not a 100% sure if I found the problem but I think it lays down in wsgidav or cherrypy.

The connection timeout has to be increased from 10 second to something bigger. I'm not 100% sure where this should be put as I tried putting it in run_server.py:

```
        server = wsgiserver.CherryPyWSGIServer(
            (config["host"], config["port"]),
            app,
            server_name=version,
            timeout=400
            )
```

but that didn't help. Any pointers on where it could be overwritten would be great.

**Comment by plenart** [comment] 2015-06-19 16:32
Hi,
is there any update on that issue? Im occuring same problem.

**Comment by shoeper** [comment] 2015-06-19 17:23
I can confirm that seafdav works without problems.

**Comment by plenart** [comment] 2015-06-19 19:44
no it doesnt work w/out problems.

2015-06-19 16:16:51,428]:  Traceback (most recent call last):
  File "/srv/seafile/seafile-server-4.2.2/seahub/thirdpart/wsgidav/error_printer.py", line 43, in __call__
    for v in app_iter:
  File "/srv/seafile/seafile-server-4.2.2/seahub/thirdpart/wsgidav/request_resolver.py", line 201, in __call__
    for v in app_iter:
  File "/srv/seafile/seafile-server-4.2.2/seahub/thirdpart/wsgidav/request_server.py", line 113, in __call__
    app_iter = method(environ, start_response)
  File "/srv/seafile/seafile-server-4.2.2/seahub/thirdpart/wsgidav/request_server.py", line 738, in doPUT
    self._fail(e)
  File "/srv/seafile/seafile-server-4.2.2/seahub/thirdpart/wsgidav/request_server.py", line 128, in _fail
    raise e
DAVError: DAVError(500 Internal Server Error: An internal server error occurred
    Source exception: '')

[2015-06-19 16:16:51,430]:  e.srcexception:

[2015-06-19 16:16:51,827]:  Input stream not completely consumed: closing connection
[2015-06-19 16:16:51,848]:  Adding 'Connection: close' header

**Comment by shoeper** [comment] 2015-06-19 19:49
Then provide some further information, please.
 * Do you have a 64 bit os and which is it? 
 * What are your webserver timeouts. 
 * Which webserver to you use (including its version). 
 * How much space do you have in your webservers tmp directory and in /tmp. 
 * What kind of server are you using? 
 * Are there any entries in your webserver logs that may be helpful?

**Comment by plenart** [comment] 2015-06-22 10:49
Its arch linux arm on Cubox-i, server is for rspi2
Web server is nginx 1.8, everything is default.
tmpfs                      1008M  624K 1007M   1% /tmp

dont know if this helps:
seafdav.access.log.1
P/1.1" 401 142 "-" "android-cloud-api - Android 5.0.2"
IP - - [19/Jun/2015:17:23:30 +0200] "PROPFIND /seafdav/My%20Library/oneplus/titanium/com.cyngn.fota-20150616-080017.tar.gz.tacitpart HTTP/1.1" 401 142 "-" "android-cloud-api - Android 5.0.2"
[19/Jun/2015:17:23:31 +0200] "PROPFIND /seafdav/My%20Library/oneplus/titanium/com.cyngn.fota-20150616-080017.tar.gz.tacitpart HTTP/1.1" 404 420 "-" "android-cloud-api - Android 5.0.2

**Comment by shoeper** [comment] 2015-06-22 12:06
can you upload files greater than 2G?

**Comment by plenart** [comment] 2015-06-22 13:02
i havent tried. Can do it on Thursday/Friday... why 2G?

**Comment by shoeper** [comment] 2015-06-22 13:09
some 32 bit setups do not support bigger uploads. Seafile Desktop client works anyway (no matter how big your files are).

**Comment by plenart** [comment] 2015-06-22 13:39
what setups? this one is for rspi, i dont see any problem why 32bit cpu cant handle >4g files. Its mobile client. In that case.. is it seafile server bug .. .or client or?

**Comment by shoeper** [comment] 2015-06-22 13:46
E.g. apache does not support it. I'm not sure about nginx. Uploading big files via webserver can have many issues.

Nginx also saved large posts to /tmp, I'm not sure if that has been fixed in 1.8 - if not that could also be an issue.

And espacially on 32-bit systems are problems with 32-bit uploads. So I don't know if it's a seafile issue but there are many other factors which could lead to issues and we should first make sure they are not relevant here.

**Comment by plenart** [comment] 2015-06-22 14:36
is there any other option how to upload that big files into seafile w/out any issues?

**Comment by plenart** [comment] 2015-06-22 14:36
do you think owncloud has the same problems?

**Comment by shoeper** [comment] 2015-06-22 14:39
Thats where I know those problems from.

**Comment by shoeper** [comment] 2015-06-22 14:39
You can use seafile desktop client to upload big files.

**Comment by plenart** [comment] 2015-06-22 14:43
ah so from mobile/tablet its not possible? i can ftp files.. directly on the server but question is how to "insert" them into seafile

**Comment by plenart** [comment] 2015-06-22 14:45
just thinking if dropbox/ggl drive can handle >4G using their mobile clients.

**Comment by shoeper** [comment] 2015-06-22 14:54
It is possible. It just depends on your server hardware and configuration. You cannot compare cubox-i with google or amazon servers.

**Comment by plenart** [comment] 2015-06-22 15:17
agree, but i dont know architecture/mechanism how do you handle it. So is it casched in web server etc...? does it worth to tune it? Is it possible with nginx? or there are HW limitations?

**Comment by shoeper** [comment] 2015-06-22 17:11
You have to debug this yourself.
Things you could check
 * does your webserver support large file uploads (on arm and 32-bit)
 * have you set it up properly
 * does it use a temp directory for large post requests? If so is there enough space?
 * have you setup proper timeouts?
 * have you configured seafile properly?

Furthermore this issue was initially about WebDAV - afaik the Seafile mobile app does not use webdav.

**Comment by shoeper** [comment] 2015-06-22 18:39
I did successfully upload a 5,6G file. As I've worked out here https://github.com/haiwen/seafdav/issues/9 the server needs to much time to index files if they are big. This leads to clients closing connections which stops indexing the file and leads to a failed (0kb) upload. In short: as more power your server has, as bigger are the files you can upload via webdav.

Via browser I can also upload larger files (7,6 GiG tested) had not have time to test it via Seafile Android app so far.

**Comment by plenart** [comment] 2015-06-22 20:35
you are right, i used foldersync + webdav. In that case, any hints how to setup that >4g file (how to tune all the points mentioned properly) upload using webdav? your hints are good but ill probably need to dig into more details per item...

**Comment by plenart** [comment] 2015-06-23 09:43
Ok, i tried upload 500mb file...using webdav ... it was uploading up to 100% then that process below forked, cpu was utilized for few seconds...and then upload of that file was restarted...

after this no error inside seafdav log , i applied your settings you mentioned in haiwen/seafdav#9.


No idea really ;-( HW is cubox i 4cores/2gb ram

[06/18/15 12:31:51] seafile-controller.c(88): spawned seaf-server, pid 22688
[06/18/15 12:31:51] seafile-controller.c(398): pid file /srv/seafile/pids/seafdav.pid does not exist
[06/18/15 12:31:51] seafile-controller.c(73): spawn_process: /usr/sbin/python2.7 -m wsgidav.server.run_server runfcgi --log-file /srv/seafile/logs/seafdav.log --pid /srv/seafile/pids/seafdav.pid --port 8080 --host localhost
[06/18/15 12:31:51] seafile-controller.c(88): spawned /usr/sbin/python2.7, pid 22689

**Comment by plenart** [comment] 2015-06-23 14:48
Ok, i tried upload 500mb file...using webdav ... it was uploading up to 100% then that process below forked, cpu was utilized for few seconds...and then upload of that file was restarted...

after this no error inside seafdav log , i applied your settings you mentioned in haiwen/seafdav#9.


No idea really ;-( HW is cubox i 4cores/2gb ram

[06/18/15 12:31:51] seafile-controller.c(88): spawned seaf-server, pid 22688
[06/18/15 12:31:51] seafile-controller.c(398): pid file /srv/seafile/pids/seafdav.pid does not exist
[06/18/15 12:31:51] seafile-controller.c(73): spawn_process: /usr/sbin/python2.7 -m wsgidav.server.run_server runfcgi --log-file /srv/seafile/logs/seafdav.log --pid /srv/seafile/pids/seafdav.pid --port 8080 --host localhost
[06/18/15 12:31:51] seafile-controller.c(88): spawned /usr/sbin/python2.7, pid 22689

**Comment by shoeper** [comment] 2015-06-24 08:24
I was able to upload 7.1 GiB file with those settings and my S4 using webdav with es datei explorer.

Make sure you have increased file size related options in seafile (see manual.seafile.com for possible config options).
Furthermore make sure you nginx body size ist big enough.
Next test with 1.8 GiB file 3.8 gib file and a file with more than 4 GiB.

**Comment by plenart** [comment] 2015-06-24 18:09
i tried to upload 500mb file from web-browser... at the end it says - Bad Request

nothing inside http/seafile log... any ideas?

**Comment by shoeper** [comment] 2015-06-25 06:56
Have you increased all size limits?

**Closed** 2016-02-09 22:42 UTC
