### ISSUE TITLE
Video files were interrupted.

### ISSUE THREAD

**Issue by haijunsu** [haiwen/seafile#1768] opened 2016-09-26 14:51 UTC
Server environment: Ubuntu 16.04, behind apache server.
Seafile server version: 5.1.10
Client ios 10 (iphone 7, iphone 6+) 
Client setting: 
* Auto Upload: ON
* Upload Videos: ON
* Wifi Only: ON
* Background Upload: ON
Error:
Almost all video files were interrupted. The MOV files cannot be played by any video player. Video play reported format error.

**Comment by marcusm1009** [comment] 2016-09-27 19:44
I can confirm this, here behind nginx - Server Ubuntu 15.x
Movie Files are also corrupt, if they are manually uploaded.

**Comment by npulz** [comment] 2016-09-28 08:25
Hi,

Running Ubuntu server 16.04 with apache.
Seafile pro server 5.1.18

Client ios 10 (iphone 6)

Have the same issue as above. Image files are uploading without errors.
.mp4 files are uploading, but looks like the app is crashing on .MOV files.

The app just crash and goes to apple home screen. Tried to turn off video upload, and no issue.

**Comment by agilastic** [comment] 2016-10-01 19:23
Same here:
Linux  3.16.0-4-amd64 
Debian 8u3
seafile-server Version: 6.0.2
Client: iOS 10

Really short MOV Videos are playable ... the Rest is unplayable on the Desktop.. (maybe random luck...)

Auto Upload: ON
Upload Videos: ON
Background Upload: ON

Example: 
IMG_1040.mov was transfered via Seafile  (corrupted)
IMG_1040_2.mov was transfered via E-Mail (working)

 ls -nl IMG_1040.mov
-rw-r--r--@ 1 501  20  34747761  1 Okt 20:23 IMG_1040.mov
ls -nl IMG_1040_2.mov
-rw-r--r--@ 1 501  20  34747761  1 Okt 20:31 IMG_1040_2.mov
-> Filesize looks the same...


Looking the head content via hexdump:

hexdump -n60 IMG_1040.mov
0000000 ad c4 d4 5d 54 09 72 ec 8c ae 7d de 91 18 db cb
0000010 6d 74 cd a2 11 49 ed a7 ed 23 86 f8 17 e0 f0 2f
0000020 4c 22 62 b6 11 7e e3 d1 3f 57 ad 4d ed 68 49 6d
0000030 42 fb c4 c7 ce 1c 43 fb ad 1a dd be
000003c

hexdump -n60 IMG_1040_2.mov
0000000 00 00 00 14 66 74 79 70 71 74 20 20 00 00 00 00
0000010 71 74 20 20 00 00 00 08 77 69 64 65 02 11 f1 f6
0000020 6d 64 61 74 9a ff 9a ff 64 ff 64 ff 61 ff 61 ff
0000030 43 ff 43 ff 2b ff 2b ff 32 ff 32 ff
000003c
 

-> So the HEX-Content looks totally different....

**Comment by marcusm1009** [comment] 2016-10-03 07:35
If i'm right, the latest Update does not solve this issue, Right?

**Comment by agilastic** [comment] 2016-10-05 20:38
No for me it doesn't solve that issue...

**Comment by killing** [comment] 2016-10-10 04:10
Fixed in https://github.com/haiwen/seafile-server/commit/0fdc2ae04880188133f7747daa7bb0b0a59a2d7f

**Closed by killing** 2016-10-10 04:10 UTC
Labels: type-possiblyabug
