### ISSUE TITLE
Self-compiled Seafile fileserver does not respond, web downloads hang

### ISSUE THREAD

**Issue by jellysheep** [haiwen/seafile#1119] opened 2015-03-08 14:54 UTC
Hi,
I have a problem when downloading files from the seahub web interface.
I installed Seafile on a Raspberry Pi on Arch Linux, using [seafile-server (AUR)](https://aur.archlinux.org/packages/seafile-server/) and the seafile server tarball from the official seafile download website, and deployed it on the local subnet using nginx and SQLite as described in the [Arch Linux wiki entry](https://wiki.archlinux.org/index.php/Seafile).

Everything (syncing using the linux client, browsing the website) works, except downloading files through the seahub web interface (the file has just a few bytes):
Without an entry `FILE_SERVER_ROOT` in `seahub_settings.py` the download link redirects from http://192.168.1.10/repo/...ID.../...ID.../download/?p=/test.txt to http://192.168.1.10:8082/files/...ID.../test.txt. But when opening this link (in a browser or with `curl -v --cookie ...`) you get no response at all from the seafile fileserver, the browser is stuck at loading.
The port 8082 is definitively open and netstat shows seaf-server is listening on this port. I tried using nginx and `FILE_SERVER_ROOT`, but downloads are stuck as well, failing with a gateway timeout. In the `logs/` directory there is no sign that any client has made an attempt to access a file.

Is there something wrong with my configuration, or is there a bug in the raspberry build?
Should I try to install an older version of seafile?

**Comment by jellysheep** [comment] 2015-03-10 17:27
Installing version 3.1.7 does not fix this. So this seems to be a bug in the Raspberry Pi build?

**Comment by shoeper** [comment] 2015-03-10 18:05
Current version is 4.0.6.

Information on how to deploy seafile can be found here: http://manual.seafile.com/deploy/using_sqlite.html and here http://manual.seafile.com/deploy/deploy_with_nginx.html

**Comment by jellysheep** [comment] 2015-03-17 11:46
I tried using version 4.0.6, but had no success.

Apparently the Arch Linux systemd service to start Seafile is faulty. When starting seafile manually with `./seafile.sh start` and `./seahub.sh start[-fastcgi]` everything works as expected.

Thanks for providing such a nice software.

**Comment by jellysheep** [comment] 2015-03-20 12:56
I have to reopen this issue, though slightly rename it, because it is still present and not due to Arch Linux stuff.
As it can be seen [in the AUR](https://aur.archlinux.org/packages/seafile-server/) some people (e.g. @Calrama) have the same issue, that a self-compiled, correctly deployed Seafile instance hangs when downloading files.
`seaf-server` correctly listens on port 8082 (visible via netstat) but does not respond at all when requesting a file (nginx/fastcgi does not matter). Empty (zero byte) files are returned immediately, though.
As reported version 4.0.5 did not have this bug. Any ideas?

**Comment by jellysheep** [comment] 2015-03-20 13:45
I tried a few more things, and apparently the issue is caused by `libevhtp 1.2.10`. When using `libevhtp 1.2.9` downloads work as expected.
Is this an issue in libevhtp or was there some API change which seafile does not respect yet?

**Comment by jirutka** [comment] 2015-04-08 17:07
I’ve tried seaf-server with several versions of libevhtp:

* **1.2.0** (both [upstream](https://github.com/ellzey/libevhtp) and [haiwen’s fork](https://github.com/haiwen/libevhtp)), but only when [this patch](https://github.com/haiwen/libevhtp/commit/d24ad5d0542c14dce3790bb6d08589ae4019caa9) is applied (otherwise it can’t be compiled).
* **1.2.1** and **1.2.9** works fine, but only when compiled (and statically linked) with the bundled oniguruma! When system provided oniguruma is used, then when you try to download some file, seaf-server fails:

    ```
    *** stack smashing detected ***: seaf-server - terminated
    seaf-server: stack smashing attack in function <unknown> - terminated
    ```
* **1.2.10** doesn’t work even with bundled oniguruma, downloads hangs as @jellysheep described.

I’m using Gentoo Linux, so this isn’t Arch-specific issue.

**Comment by jirutka** [comment] 2015-04-08 20:02
It seems that it 1.2.9 with the system-provided oniguruma worked just by some weird coincidence, it doesn’t work anymore. :( This is weird.

**Comment by jurov** [comment] 2015-04-28 18:44
I can confirm both the problem and fix (1.2.9 with included oniguruma), on gentoo + 4.1.2 seafile server. I have attached to the stuck server process with following result. It was not possible to get it to step out of epoll_wait () by connecting in any way. I forgot to save the stacktraces, only remember that Thread 3 was in malloc() and thread 1 was in libevent's event_loop. Looks like some kind of deadlock.
```
(gdb) info threads
  Id   Target Id         Frame 
  3    Thread 0x35cc6669700 (LWP 5845) "seaf-server" 0x0000035cc8c6920b in ?? () from /lib64/libc.so.6
* 1    Thread 0x35ccb5c2780 (LWP 5839) "seaf-server" 0x0000035cc8c5c573 in epoll_wait () from /lib64/libc.so.6
```

**Comment by ellzey** [comment] 2015-11-28 04:11
Augh, wish someone would have poked me about this. After reviewing various bits of this code, (server/access-file.c for example), there was a change that can break this.

I was being harassed about pipelined requests, and I implemented a fix to do just that.

But it affected some logic that the seafile code uses, and I am completely sorry & embarrassed by saying it.

"you call resume AFTER you have sent the reply (not BEFORE)." or in short: treat it like pending data, then hit the resume button.

I would be happy to go through all this code and make sure that the order is correct.

**Comment by freeplant** [comment] 2015-11-29 11:26
@ellzey Thank you very much for the information. We will give new version of libevhtp a fully test in the next 2 weeks.

**Comment by ellzey** [comment] 2015-12-01 07:33
So here is the problem, again:

When EV_WRITE is enabled, and there is no more data that is written, then nothing happens. This was fixed in libevent2.1x. with `bufferevent_trigger` which is like `event_active` but you can trigger specific data callbacks; on top of that it becomes deferred, which is good in cases like this.

I'm trying to figure out how to emulate the function in 2.0.

**Comment by ellzey** [comment] 2016-06-12 23:48
I haven't left yet, I just pushed some testing code that gets around using libevent 2.1

https://github.com/ellzey/libevhtp/tree/feature/resume_fixes

```
Prior to this, the following logic for pause/resume was:

1. When a request is paused, both EV_READ AND EV_WRITE are disabled.
2. When a request is resumed, if there is data waiting to be sent to the
   client, a "wait for the write to finish" flag is set, and ONLY EV_WRITE
   is enabled.
3. Once that part has been fully written, the "wait for write" flag is
   unset, and EV_READ is enabled again.

This can run into issues:

When EV_WRITE is enabled, and there is no more data that is written,
then nothing happens. This was fixed in libevent2.1x. with
bufferevent_trigger which is like event_active but you can trigger
specific data callbacks; on top of that it becomes deferred, which is
good in cases like this.

The new proposed logic is as follows:
1. Same
2. When a request is resumed, if data is awaiting, instead of
   just calling bufferevent_enable(), we also call event_active
   on the underlying bufferevent's write callback.
3. When a request is resumed and ready to read, a new event
   has been created: `resume_read_ev` which (in the next
   loop) will execute the readcb once it's activated.

Other:
Added debugging stuff everywhere if enabled.
Added a clearer example of pause/resume in examples/test_pause_resume.c
```

**Comment by niol** [comment] 2017-10-19 14:50
Please see https://github.com/haiwen/seafile-server/issues/67#issuecomment-337904800 , it seems to work.

**Closed** 2018-10-29 22:52 UTC
