### ISSUE TITLE
seaf-daemon.exe (windows10) crashes, when syncing a shared + encrypted library

### ISSUE THREAD

**Issue by Jonas16** [haiwen/seafile#2046] opened 2018-05-05 12:01 UTC
The issue:
- User A creates a encrypted library
- User A shares encrypted library with B
- B tries to sync the library with the windows client (6.0.7 + 6.1.7)
- There is no prompt for a PW
- seaf-daemon crashes (without any message)
- All libraries are shown unsynced now
- Trying to download any library causes a transport error (I assume due to the crashed process)
- Closing and starting the seafile client does not work until the ccnet and the data directories are removed/renamed

What I tried already (did not help):
- Updated the client SW from 6.0.7 to 6.1.7
- let B create the lib and share it with user A
- Share not encrypted library (works)
- Delete ccnet and seafile data directory of the client and do it again

My seafile server version is 6.2.5

logfiles:
[applet.log](https://github.com/haiwen/seafile/files/1976630/applet.log)
[ccnet.log](https://github.com/haiwen/seafile/files/1976631/ccnet.log)
[seafile.log](https://github.com/haiwen/seafile/files/1976632/seafile.log)

In a zip (including crash dump):
[logscrash.zip](https://github.com/haiwen/seafile/files/1976633/logscrash.zip)

I hope that I provided all relevant information.

**Comment by Seafloweredge** [comment] 2018-11-17 20:57
I have exactly the same issue using the seafile applet on gnome-shell. 

Also see other users having the issue: [https://forum.seafile.com/t/strange-behaviour-with-encrypted-libraries/6747](url)

**Comment by eboleslawski** [comment] 2019-07-08 22:31
I just have had exactly the same issue with Seafile Client 7.0.0 for Windows 10, that is (as perfectly described by **Jonas16**):
    User A creates a encrypted library
    User A shares encrypted library with B
    B tries to sync the library with the windows client (6.2.5 or even 7.0.0 in my case)
    There is no prompt for a password at any time of the sync process
    seaf-daemon crashes (without any message)
    All libraries are shown unsynced now
    Trying to download any library causes a transport error
    Closing and starting the seafile client does not work
    Unlike **Jonas16**, I didn't try to remove/rename the ccnet and the data directories; instead I completeley reinstalled the 7.0.0 client, which works perfectly for syncing other libraries than shared/encrypted ones.
   All the above are perfectly reproducible x times.

My Seafile server is 6.3.4 community edition, running on Raspbian.

Syncing the same encrypted (but not shared) library on my laptop running Seafile Client 6.2.9 for Linux is uneventful.

Would be it of any help to check if my Linux client could sync an encrypted AND shared library or if my windows client could sync an encrypted but NOT shared (or a shared but NOT encrypted) library ?

By the way, those are unmeaningful inconveniencies regarding the fantastic job you've done so far !
Thank you very much for developing Seafile !

**Comment by killing** [comment] 2019-07-09 01:57
Hi @eboleslawski 

Do you see any dump file under C:\uesrs\username\ccnet\logs\dumps folder?

**Comment by eboleslawski** [comment] 2019-07-09 22:17
You're right.
After a fresh reinstallation of the Seafile Client v7.0.0 for Windows, I checked the "C:\user\username\ccnt\logs\dumps" folder and noted it was empty.
Then, I tried to sync the famous shared/encrypted library again .
As expected, after the client had completely downloaded the files' list (reaching the 100% list rate), it crashed again without any message.
Now the "C:\user\username\ccnt\logs\dumps" folder contains two dump files, which I've attached to this message.
Thank you for your kind assistance.
[dumps.zip](https://github.com/haiwen/seafile/files/3374975/dumps.zip)

**Comment by killing** [comment] 2019-07-10 03:08
@eboleslawski 

The problem is that "There is no prompt for a password at any time of the sync process" but the library is actually encrypted. I tested with 7.0.0 client and 6.3.x/7.0.x servers, the client always prompts for passwords when syncing a shared encrypted library.

I think your issue is somehow specialized to your server. Can you check your applet.log and seafile.log for more clue?

**Comment by eboleslawski** [comment] 2019-07-10 21:57
Hi @killing !

What I did is doing a fresh install of the WIndows client 7.0.0 again and deleting all previous client-side logs.
I did this at 11:09 PM local time.

Then, I connected the client to my server and repeated the crash process by syncing the encrypted/shared library.
I did this at **11:11 PM** precisely.
You can see in the client-side [applet.log](https://github.com/haiwen/seafile/files/3379485/applet.log) that the Seafile Client crashed at 11:12:45 with the error code: **1073741819**.
_Does this error code mean anything for you ?_

I also provide you with the new dump files ([dumps.zip](https://github.com/haiwen/seafile/files/3379493/dumps.zip)) and also with the [client-side seafile.log](https://github.com/haiwen/seafile/files/3379504/seafile.log.client-side.log).

The server-side **seafile.log** does not seem to show any clue: the warning _"Repo size compute queue size is 0"_ is repeated every 5 minutes but this has been so for a long time and I read in another post that this was not a kind of problem.
Here are the last lines of the seafile.log server-side:
[07/10/19 22:59:37] size-sched.c(96): Repo size compute queue size is 0
[07/10/19 23:04:37] size-sched.c(96): Repo size compute queue size is 0
[07/10/19 23:09:37] size-sched.c(96): Repo size compute queue size is 0
[07/10/19 23:14:37] size-sched.c(96): Repo size compute queue size is 0
[07/10/19 23:19:37] size-sched.c(96): Repo size compute queue size is 0
[07/10/19 23:24:37] size-sched.c(96): Repo size compute queue size is 0
[07/10/19 23:29:37] size-sched.c(96): Repo size compute queue size is 0

Again, thanks a lot for your help...

**Comment by nilsheller** [comment] 2020-05-15 09:33
Hi,

I've the same issue with different client versions on different connected systems.
The only option is to copy the content of the enrypted libraries in unencrypted libraries and don't use the encryption. :(

**Closed** 2020-09-16 09:54 UTC
Labels: priority-low, type-possiblyabug
