### ISSUE TITLE
Seadrive 2.0.8 not working on macOS Big Sur

### ISSUE THREAD

**Issue by Worikben** [haiwen/seafile#2394] opened 2020-11-20 16:06 UTC
I can install Seadrive client 2.0.8 or 2.0.9 on a clean install macOS Big Sur. When the program opens the appears: failed to initialized: failed to install kernel driver. Same error appears on both versions
<img width="421" alt="Schermafbeelding 2020-11-20 om 17 03 59" src="https://user-images.githubusercontent.com/27916613/99821766-b93c9500-2b52-11eb-8da9-e2e0541e34a9.png">

**Comment by feiniks** [comment] 2020-11-23 03:13
As far as I Know，the version of seadrive 2.0.9 should work perfectly on macOS Big Sur.You can search related issues on our forum.https://forum.seafile.com/

**Comment by Worikben** [comment] 2020-11-23 06:46
I can say that version 2.0.9 didn’t work on macOS Big Sur on a clean install.
Version 2.0.8 works on Mojave and Catalina. Upgrading from on of these macOS version keeps Seadrive working. So it only appears with a clean install, for twice now. Even after resetting SCM / NVRAM and PRAM

**Comment by killing** [comment] 2021-03-18 05:51
This is usually not a bug. We had some users having issues in the system that causes this issue. You can post your seadrive-gui.log on our forum and we'll have a look at it. For now I'll close this issue.

**Closed by killing** 2021-03-18 05:51 UTC

**Comment by dumboxp** [comment] 2021-07-24 18:23
I also got the same issue several times in the past and again under macOS BugSur 11.5 - but (at least for me), it was caused by an outdated version of **macFUSE** which allows you to extend macOS’s native file handling capabilities via third-party file systems (see https://osxfuse.github.io/). 

Make sure you installed or updated macFUSE to its latest version via the _System Preferences > macFUSE > Update FUSE_ and reboot your Mac.
