### ISSUE TITLE
Moving a shared folder breaks sync

### ISSUE THREAD

**Issue by digi24** [haiwen/seafile#1156] opened 2015-03-26 18:30 UTC
Using Seafile 4.1.0 on Debian64 with sqlite, I am experiencing problems with uploading from the Windows client.  It always stops after the first batch of files is uploaded.
in seafile.log:
```
[03/26/15 19:07:57] virtual-repo.c(685): Failed to get virt repo e9b6a645-7.
[03/26/15 19:07:57] virtual-repo.c(685): Failed to get virt repo 28742890-0.
...
```
I narrowed the problem down:
The failed virtual repos cannot be seen from the web.  They are formerly shared folders which disappeared when the folder themselves where moved to another folder using the Web-GUI.

To reproduce: Share a folder and move it somewhere using the Web-GUI.  Then try syncing it with a larger amount of new data on the Windows client. 

Expected behaviour: Either update the location the share is pointing to or output an error that a shared folder cannot be moved.

Question: is there a way I can get rid of these orphaned shares without deleting the whole installation?  I tried creating new shares on the original folders and deleting them as well as moving the folders to the prior location.  But it only increased the number of orphaned shares.  Is it sufficient if I just delete the problematic repo_ids from seafile.db?

**Comment by killing** [comment] 2015-03-27 02:12
Hi,
A virtual repo is removed when the corresponding folder is removed/moved.
How do you sync with a repo that's already removed?

2015-03-27 2:30 GMT+08:00 digi24 <notifications@github.com>:

**Comment by digi24** [comment] 2015-03-27 06:52
In my case it was not removed.  I moved the shared folder via the Web-GUI into a subfolder.  In that moment the share disappeared from my Windows client and everything else seemed fine.  then I noticed that another client, syncing to the parent library and uploading lots of stuff stopped syncing and even after manually restarting always stopped again after a couple of minutes.  

In the logs I saw the failed to get virt repo messages and by inspecting the tables in seafile.db I saw that these repo_ids referred to the previously shared folders.

**Comment by soakes** [comment] 2015-08-11 19:33
Hi, I am now experencing the exact same issue while uploading a load of data.  Durning this upload I renamed a folder which wasn't being synced at that time to a new name and shortly after then my client kept throwing orange exclamation marks which then got me to login to the server and check the logs.  

` ==> seafile.log <==
[08/11/2015 08:24:14 PM] ../common/mq-mgr.c(60): [mq client] mq cilent is started
[08/11/2015 08:24:14 PM] ../common/mq-mgr.c(106): [mq mgr] publish to hearbeat mq: seaf_server.heartbeat
[08/11/2015 08:24:14 PM] listen-mgr.c(115): listen on port 12001 for block tranfer
[08/11/2015 08:25:14 PM] virtual-repo.c(685): Failed to get virt repo e2334a12-0.
[08/11/2015 08:26:28 PM] virtual-repo.c(685): Failed to get virt repo e2334a12-0.
[08/11/2015 08:27:44 PM] virtual-repo.c(685): Failed to get virt repo e2334a12-0.`

As you can see its the exact same issue. 

I must admit I am not using the very latest version, I am still using version 4.1.2 however from the patch notes I haven't found anything relating to this bug/fix and so I dont believe an update would curse this.

For your info, this problem started happening as soon as I renamed a folder on my mac using finder.  I also did have the website open at the same time but nothing was changed within website as I was just browsing content.

Does anyone know how I can fix this? as seafile is now not syncing content, its trying but failing every time, its like when it hits an error, it just keeps trying to do the same thing rather then skip it.

I would like to know if theres anything I can do to rescue the system/data or is this the case of wipe data and reload everything? which is kinda annoying as several people are effected.

Kind Regards,

Simon

**Comment by killing** [comment] 2015-08-12 01:57
@soaks What client version and OS do you use? Can you find errors in the client's seafile.log?

**Comment by soakes** [comment] 2015-08-12 10:22
Hi @killing, the client I am using is version 4.1.6 for OSX, as for OS version its OSX 10.10.3 (latest).  I will update the server and client hopefully later when I have a few more minutes to do it as I have two servers which needs doing.

I had a look at the logs for the client when the probelm arrose but I didn't see anything adnormal in them.

I managed to track down the issue which was stoping the client from syncing correctly by running fsck (which showed nothing wrong btw) but when I ran the GC as there was a lot of data to be removed showed that one of the repos was corrupted.  However even if you gave the repo name to fsck -r it still did't fix it as it said there was no problems. I even tried to run fsck going though all the repos but that didn't fix anything either.  I tried a few other things as well and google wanst much help either so in the end I got desperate and trashed the corrupted repos data files which then created another issue.

So, what I have done is, I found that the repo names are also in the mySQL DB and so I have manauly pureged the corrupted statment from the Repos table.  After re-running fsck and gc it now goes though all cleanly with no errors or anything.

So far, it all apears to be running fine, but I still have a lot of data to re-upload (around 40GB more) and will know more in a few hours if the problem is still resolved but after uploading a small amount of data last night, the problem was still gone away so I believe its now fixed.

Its still rather annoying I must say but it seems to of been caused by renaming an existing repo so my temp solution has been to create one rather large repo where there is no chance of name changes in the future.  

I will keep an eye on the situration and hopes it doesn't return, if it does, I may just have to rebuild the server *growns*.

**Comment by killing** [comment] 2015-08-13 03:42
@soakes Can you describe the steps for reproducing the error? And there should be error logs in the seafile.log of the client? What's the logs? What error does the server returns?

**Comment by soakes** [comment] 2015-08-13 09:58
Hi @killing.  Unfortunately as I needed it back online ASAP, I went to a few desperate messures.  All I can tell you is, this happened while I was uploading a large chunk of data and during this time I renamed several folders and even some repos.

As to logs, usualy I have/keep them but unfortunately the server and client was reinstalled for safety (latest versions now) and so they are no more.  I even trashed the local seafile dir which contains the hidden files so they are no more either.  Sorry.

If this issue returns (hopefuly it wont), I will try and reproduce it.  Right now I do not what to try and break my system due to 50+GB of data has been re-uploaded and I dont have the time to do it again.

Sorry, as much as I want to find the bug and help you to squish it, I don't currently have the time to mess around re-uploading data as its heavly used daily.  If I get some free time in the next couple of days, I will make another new server and try and break it.  If I can' I will provide full steps on how you can do the same so we can get this bug squshed.

**Closed** 2016-02-15 08:16 UTC
