### ISSUE TITLE
seaf-cli symlink support still broken

### ISSUE THREAD

**Issue by khmseu** [haiwen/seafile#1991] opened 2017-11-27 17:15 UTC
To make things work, seafile needs to use lstat(), not stat(). (If in doubt, see the man pages.)

**Comment by shoeper** [comment] 2017-11-28 13:31
This is a duplicate of https://github.com/haiwen/seafile/issues/288

Simply using lstat is NOT going to solve the issue as you can read above.

**Comment by khmseu** [comment] 2017-11-30 09:40
Actually, what I read there is that this was supposed to have been fixed. I also see code to handle symlinks in the sources. However, if you never call lstat, this code will never have a chance to actually trigger.
After making this simple change, I see that at least the client has stopped to follow symlinks; it seems to now ignore them, which is suboptimal but still much better than before.

In short, while this is certainly related to #288, it doesn't seem to duplicate anything said there, nor does it seem to be obsoleted by anything there.

Apart from that, I am somewhat surprised that  four years haven't been enough to solve this issue, which git (from which seafile is supposedly derived) has solved pretty much forever. Nor do the comments in places like #288 explain what is so hard about the problem.

**Comment by shoeper** [comment] 2017-11-30 10:25
It is about the very same issue.

Also it is at least questionable if it is an issue or not. E.g. Dropbox also follows symlinks.

And there actually is explained why it hasn't been changed. This clearly is a duplicate.

**Closed** 2018-06-05 22:30 UTC
