### ISSUE TITLE
seafile-cli not working on arm machine

### ISSUE THREAD

**Issue by txchen** [haiwen/seafile#306] opened 2013-07-31 00:29 UTC
CPU: Marvell Kirkwood  Feroceon 88FR131 rev 1 (v5l)
CPU architecture: 5TE

compiled the client from src: http://seafile.googlecode.com/files/seafile-latest.tar.gz

'seaf-cli start' succeeded, but when I download a library, it will stuck at:

```
Library xxxxxxxxxxxxxxxxxx will be downloaded to /root/seafilerepo
```

for about 1 minute and then throw the following error:

```
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 633, in <module>
    main()
  File "/usr/bin/seaf-cli", line 629, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 384, in seaf_download
    email)
  File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/usr/local/lib/python2.7/dist-packages/ccnet/rpc.py", line 92, in call_remote_func_sync
    req_id = self._start_service(client)
  File "/usr/local/lib/python2.7/dist-packages/ccnet/rpc.py", line 36, in _start_service
    raise SearpcError("Error received: %s %s (In _start_service)" % (rsp.code, rsp.code_msg))
pysearpc.common.SearpcError: Error received: 511 Unknown service (In _start_service)
```

then the seaf-daemon process will disappear.

I also tried to manually launch the seaf-daemon:

```
seaf-daemon -c /root/.ccnet -d /root/.seafile-client/seafile-data -w /root/.seafile-client/seafile -D all -l -
```

It will crash if I start a download, output is:

```
** Message: Set debug flags 0x7e

[07/30/13 17:24:51] seaf-daemon.c(434): starting seaf-daemon 1.7.1.1
[07/30/13 17:24:51] ../common/mq-mgr.c(60): [mq client] mq cilent is started
[07/30/13 17:24:51] ../common/mq-mgr.c(106): [mq mgr] publish to hearbeat mq: seafile.heartbeat
[07/30/13 17:24:51] ../common/gc-core.c(313): No blocks. Skip GC.
**
Ccnet:ERROR:ccnet-client.c:631:handle_packet: assertion failed: (0)
Aborted
```

Here is ccnet.log, FYI:

```
[07/30/13 17:20:15] ccnet-daemon.c(168): starting ccnet client 1.3.4
[07/30/13 17:20:15] ccnet_net_bind_v4: Bind error: Address already in use
[07/30/13 17:20:16] ../common/session.c(365): Accepted a local client
[07/30/13 17:20:16] ../common/session.c(365): Accepted a local client
[07/30/13 17:20:16] ../common/session.c(365): Accepted a local client
[07/30/13 17:20:25] ../common/session.c(365): Accepted a local client
[07/30/13 17:21:34] ../common/peer.c(932): Local peer down
[07/30/13 17:21:34] ../common/peer.c(932): Local peer down
[07/30/13 17:21:34] ../common/peer.c(932): Local peer down
[07/30/13 17:21:34] ../common/processor.c(223): [Proc] Shutdown processor mqserver-proc(-1002) for bad update: 515 peer down
[07/30/13 17:21:34] ../common/processor.c(297): [Proc] peer 52c4e47dc1, Shutdown processor service-stub-proc(1001) for bad response: 515 peer down
[07/30/13 17:21:34] ../common/processor.c(297): [Proc] peer 52c4e47dc1, Shutdown processor service-proxy-proc(-1001) for bad response: 515 peer down
[07/30/13 17:21:34] ../common/session.c(365): Accepted a local client
[07/30/13 17:21:34] ../common/peer.c(932): Local peer down
[07/30/13 17:21:34] ../common/peer.c(932): Local peer down

```

BTW, I tried to build the same src on an x64 machine (ubuntu 13.04), cannot repro this issue, so I think it is ARM specific bug.

**Comment by txchen** [comment] 2015-02-06 05:54
I think latest version (4.0.5) still has this issue.

**Comment by Q-efx** [comment] 2015-02-21 10:30
Damn, was thinking to put it on my little NAS ;( The new raspi gets more and more tempting lol

**Comment by piafinho** [comment] 2015-02-21 10:53
I Run it in my QNAP ts-112.
Just need to do the "echo 2 > /proc/cpu/alignment" so that when I start the process, it works.

**Comment by davygravy** [comment] 2015-05-04 02:53
Ditto that for 4.2.0.  It was some work to get it to build on Debian Armel...  This alignment bug is still present.

**Comment by Chilledheart** [comment] 2015-05-04 06:44
Hmm, personally, I [made a patch][1] which should solve the alignment problem described by @txchen . And it works well on my armv7 chromebook.

I am not sure if it works on your device but can you test this patch (against latest ccnet)  ? 

> [PATCH] [remove obsolete buffer.c][1]

BE AWARE This is a non-official patch and there is no guarantee provided. Don't use it on important data.

[1]: https://gist.github.com/Chilledheart/81bea16e007c6d426355

**Comment by davygravy** [comment] 2015-05-04 11:32
@Chilledheart : Thanks, will patch and recompile later this week.  Will let you know once I've tried it.

**Comment by davygravy** [comment] 2015-05-07 03:10
@Chilledheart : I applied the patch, carefully built, and tested it.  The patch applies cleanly, and the patched code builds successfully.

With normal alignment, I see this:  http://dpaste.com/05EGP6Y

With alignment set to 2 (fixup), it works normally (though, perhaps with a bit of a performance hit).

I would suggest getting this confirmed by another Kirkwood ARM5 user.   If you'd like, I can bring this issue up at the doozan debian site (Kirkwood-oriented).  

Do you think there could be other instances of alignment problems in the code?

**Comment by davygravy** [comment] 2015-05-07 16:31
@Chilledheart : You mentioned that "it works well on" your ARMV7 chromebook.  Specifically, does it _not_ work if you _don't_ patch it?

I used chardet 1.0 instead of the newest 2.3.0.  I wonder if that could be a snag?

**Comment by Chilledheart** [comment] 2015-05-07 17:18
@davygravy I am not sure, maybe it just works on ARMv7 boards even with misaligned memory access. I think there are still some thing different between these devices and it turns out that my patch still doesn't fix your issue at all. 

I don't think different versions chardet matters much here, but anyway if you are talking about chardet, do you running seafile server on your arm device?

**Comment by davygravy** [comment] 2015-05-08 02:53
@Chilledheart : Yes, I'm running it now (as a trial/test) on a 1.2GHz Kirkwood device (Seagate Dockstar) that has Debian Jessie installed.  It runs well, and later this weekend I'd like to see how it works with Nginx serving the pages, instead of the built-in server.

I posted my findings and a 4.1.2 server tarball here :  [Seafile on Debian Armel](http://forum.doozan.com/read.php?2,21772,21772#msg-21772)  in the hope that other users will experiment, tweak and investigate the alignment problem.

**Comment by davygravy** [comment] 2015-05-09 18:11
Any chance that the -Wcast-align flag could detect these?

Or is it strictly gdb that is going to find them?

**Comment by Chilledheart** [comment] 2015-05-09 21:11
@davygravy that's a quite handy flag.

**Comment by davygravy** [comment] 2015-05-10 18:57
@Chilledheart : Handy flag, yes.  This is not the "exhaustive & all-inclusive list", since it was applied **only** to the lib directory in the source, after applying your patch.   There *could* be many, many more, in the other directories.   Granted, a sizable number of those detected could be *false* positives.   

What I find a bit odd is that this Issue #306 was opened by @txchen in July 2013 - we approach 2 years now - and it still festers.  I'm expecting that unless someone exclusive of the owners fixes it, we should not be surprised if it remains "Unassigned" or even moved to "Won't Fix".   

:) Handy, yes.   Right now I can't play "Handyman", though-I've got other projects on the stove.  The downside of open source is that sometimes a defacto "Won't Fix" gets stamped on anything that isn't immediately profitable.

**Closed** 2020-09-16 09:13 UTC
