### ISSUE TITLE
Some videos have no image when playing, but there is sound (seafile-pro-server_8.0.4)

### ISSUE THREAD

**Issue by aminecmi** [haiwen/seafile#2466] opened 2021-06-21 19:26 UTC
I'm trying to solve some playback issue with videos.

Multiple mp4 and mov files won't play. There's sound, but no image at all.

I installed moviepy and ffmpeg.

What else could I do to fix this ?

Thanks.

**Comment by killing** [comment] 2021-06-23 08:31
That depends on which codecs the browser supports and which codec your video uses. Since it's not a bug in seafile, I'll close this first.

**Closed by killing** 2021-06-23 08:31 UTC

**Comment by aminecmi** [comment] 2021-06-23 08:39
The same file, plays without any issue with other cloud apps like owncloud. How can’t this be a seafile issue ?

**Comment by aminecmi** [comment] 2021-06-23 19:24
I just wanted to add some details.

This mov video has the same error as #2465 
<img width="552" alt="Nothing" src="https://user-images.githubusercontent.com/510304/123155567-8f40ad80-d468-11eb-85ef-610d4ce21ba0.png">

This mov  has only sound, yet, seems to need the same codec as the previous one
<img width="542" alt="Sound only" src="https://user-images.githubusercontent.com/510304/123155577-91a30780-d468-11eb-8242-c5a883925419.png">

And this works.
<img width="536" alt="Works" src="https://user-images.githubusercontent.com/510304/123155588-949df800-d468-11eb-9a72-afa2574ff641.png">

This mp4 video has only sound
<img width="533" alt="sound only mp4" src="https://user-images.githubusercontent.com/510304/123156162-43dacf00-d469-11eb-84e0-60ba2eace41b.png">

And this one works fine
<img width="550" alt="Capture d’écran 2021-06-23 à 21 22 56" src="https://user-images.githubusercontent.com/510304/123156171-463d2900-d469-11eb-9400-e822221ffc94.png">

Is it really a codec issue ?

**Comment by jobenvil** [comment] 2021-11-15 19:47
@aminecmi Yes, it's a H.265 issue. Try with Edge and it will work. Afortunatedly it denpends on the browser. See [here](https://support.google.com/chrome/thread/127402264/does-google-chrome-support-hevc-h-265-codec?hl=en).
