### ISSUE TITLE
Design bug on seafile.com

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1089] opened 2015-02-18 14:45 UTC
There is a small design bug, maybe you'll want to fix it. See
![Design Bug](https://mno.pw/0796)

For me it is there when I go to http://seafile.com/ (then it redirects to http://seafile.com/en/home/)
When I directly go to http://seafile.com/en/home/ the bug is not there.
It's a bit strange the bug is not always there but sometimes. Hope this helps a bit.

**Comment by shubhank008** [comment] 2015-02-18 22:23
I would like to add in this same ticket, not sure if its intentional or not, but on shared file/folder link download page, the footer is not visible ? I can see the code of footer being present in page's source code and the element inspecter but it doesn't show up in browser and instead a plain white area shows

**Comment by onovy** [comment] 2015-03-28 12:38
![screenshot](https://cloud.githubusercontent.com/assets/1649603/6881058/7d4e4836-d54f-11e4-9e8a-14b6cdb92c85.png)

Same problem on Private instalation of Seafile. Using Seafile 4.1.1, Google Chrome on Linux. When I open my Seahub, design is ok. But when i [press CTRL+R, arrows is doubled.

**Comment by freeplant** [comment] 2015-10-22 07:46
Since I can't reproduce the bug, I close it.

**Closed by freeplant** 2015-10-22 07:46 UTC
Labels: bug

**Comment by shoeper** [comment] 2015-10-22 07:55
It has been there on the old website ;)
