### ISSUE TITLE
Avatars Broken

### ISSUE THREAD

**Issue by shamowfski** [haiwen/seafile#1091] opened 2015-02-20 01:50 UTC
Hello All,

I am getting frustrated trying to get avatars to work. I have reinstalled multiple times and have never gotten them to work.

My install is 4.0.6 using https,nginx, on Centos 6.6 x64 with selinux disabled. User that installed seafile is 'seafile' and nginx is running as user 'seafile'. CSS/Images work, file uploads and downloads work, but avatars are a broken image and while it's not a huge deal, it makes it look like shit.

Default avatar doesn't display. If I upload a new avatar it says that it uploaded successfully but logs show a 404 trying to display the avatar. This is because when i browse down into the avatars folder, the file name it's trying to pull doesn't exist.

My seahub_settings.py:

SECRET_KEY = "XXXXXXXXXXXXXXXXXXXX"

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'seahub-db',
'USER': 'root',
'PASSWORD': 'XXXXXXX',
'HOST': '127.0.0.1',
'PORT': '3306',
'OPTIONS': {
'init_command': 'SET storage_engine=INNODB',
}
}
}

FILE_SERVER_ROOT = 'https://files.XXXXXXXXXXXXX.com/seafhttp'

nginx conf:

server {
listen 80;
return 301 https://$server_name/$1; # force redirect http to https
}
server {
listen 443;
ssl on;
ssl_certificate /etc/ssl/xxxxxx.com.au.crt;
ssl_certificate_key /etc/ssl/xxxxxxx.com.au.key;
location / {
fastcgi_pass 127.0.0.1:8000;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param PATH_INFO $fastcgi_script_name;

      fastcgi_param   SERVER_PROTOCOL       $server_protocol;
      fastcgi_param   QUERY_STRING        $query_string;
      fastcgi_param   REQUEST_METHOD      $request_method;
      fastcgi_param   CONTENT_TYPE        $content_type;
      fastcgi_param   CONTENT_LENGTH      $content_length;
      fastcgi_param   SERVER_ADDR         $server_addr;
      fastcgi_param   SERVER_PORT         $server_port;
      fastcgi_param   SERVER_NAME         $server_name;
      fastcgi_param   HTTPS               on;
      fastcgi_param   HTTP_SCHEME         https;

      #fix IE
      add_header X-UA-Compatible "IE=Edge,chrome=1";

      access_log      /var/log/nginx/seahub.access.log;
      error_log       /var/log/nginx/seahub.error.log;

  }
  location /seafhttp {
      rewrite ^/seafhttp(.*)$ $1 break;
      proxy_pass http://127.0.0.1:8082;
      client_max_body_size 0;
      proxy_connect_timeout  36000s;
      proxy_read_timeout  36000s;
  }
  location /media {
    root /home/seafile/tgap/seafile-server-latest/seahub;
  }

 location /seafdav {
    fastcgi_pass    127.0.0.1:8080;
    fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
    fastcgi_param   PATH_INFO           $fastcgi_script_name;

    fastcgi_param   SERVER_PROTOCOL     $server_protocol;
    fastcgi_param   QUERY_STRING        $query_string;
    fastcgi_param   REQUEST_METHOD      $request_method;
    fastcgi_param   CONTENT_TYPE        $content_type;
    fastcgi_param   CONTENT_LENGTH      $content_length;
    fastcgi_param   SERVER_ADDR         $server_addr;
    fastcgi_param   SERVER_PORT         $server_port;
    fastcgi_param   SERVER_NAME         $server_name;

    fastcgi_param   HTTPS               on;

    access_log      /var/log/nginx/seafdav.access.log;
    error_log       /var/log/nginx/seafdav.error.log;
}
}

Any help would be greatly appreciated as I would prefer to use seafile, but can't roll it out if I can't get this fixed.

Thanks,

**Comment by lins05** [comment] 2015-02-20 02:19
The avatar folder is `seafile-server-4.0.6/seahub/media/avatars`, which is actually a symlink to `<top-folder>/seahub-data/avatars`, which is created by the `setup-seafile.sh` script.

Check if that file is created correctly:

```bash
ls -l seafile-server-4.0.6/seahub/media/avatars
```

Also:

- Is there any errors in `/var/log/nginx/seahub.access.log` or `/var/log/ngnix/seahub.error.log`?
- [Can you nginx follow symlinks?](http://stackoverflow.com/questions/12624358/nginx-not-following-symlinks)

**Comment by lins05** [comment] 2015-02-20 02:21
Closed because this is a duplicate of https://forum.seafile-server.org/t/avatars-display-broken-image-link-cant-upload-new-avatars/599.  @shamowfski Let's discuss it there.

**Closed by lins05** 2015-02-20 02:21 UTC
